### ISSUE TITLE
Light shaper proportions

### ISSUE THREAD

**Issue by vafu** [TheSlowGrowth/MonomeArcClone#4]
Hello, i have a question regarding positioning of light shaper windows. It’s unclear for me how are they positioned on the ring. Attaching an image. 
![Изображение PNG](https://user-images.githubusercontent.com/12833042/83583840-149bac00-a54e-11ea-843b-6c52ef51d631.png)
Seems that these dimentions are not 1:1

**Comment by TheSlowGrowth** [comment]
Sorry, I somehow didn't see this before...

The dimensions are 5:1, as stated in the drawing. 
x/y are not critically important. If you machine this yourself you can pretty much set this "by eye" to any proportion that looks good. I designed it so that the LEDs are in the center of the cutouts.

The inner and outer diameter are important, though.
